# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.vfs.watch=false
org.gradle.daemon.idletimeout=60000
kotlin.daemon.jvm.options=-Dkotlin.daemon.idle.timeout=60
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
ksp.incremental=false
ksp.useKSP2=true
android.disallowKotlinSourceSets=true
android.defaults.buildfeatures.resvalues=false
android.uniquePackageNames=false
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=false
android.builtInKotlin=true
android.newDsl=true

